FROM php:8.3-cli-bookworm
ENV XDEBUG="false"
ENV COMPOSER_ALLOW_SUPERUSER=1

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        libz-dev \
        libpq-dev \
        libjpeg-dev \
        libpng-dev \
        libfreetype6-dev \
        libssl-dev \
        libmcrypt-dev \
        libmagickwand-dev \
        nano \
        htop \
        libxml2-dev \
        libzip-dev \
        unzip \
        && rm -r /var/lib/apt/lists/*

# Install soap extention
RUN docker-php-ext-install soap exif pcntl zip pdo_pgsql bcmath sockets

#RUN MAKEFLAGS="-j $(nproc)" pecl install  -o -f grpc && docker-php-ext-enable grpc

#--------------------------------------------------------------------------
# Composer:
#--------------------------------------------------------------------------

# Install composer and add its bin to the PATH.
RUN curl -s http://getcomposer.org/installer | php && \
    echo "export PATH=${PATH}:/var/www/vendor/bin" >> ~/.bashrc && \
    mv composer.phar /usr/local/bin/composer
# Source the bash
RUN . ~/.bashrc

#--------------------------------------------------------------------------
# Final Touch
#--------------------------------------------------------------------------

ADD ./.deploy/php/local.ini /usr/local/etc/php/conf.d

RUN usermod -u 1000 www-data && groupmod -g 1000 www-data

WORKDIR /var/www

EXPOSE 8080
VOLUME ["/var/www"]
CMD ["bash"]
